apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-hello
  template:
    metadata:
      labels:
        app: flask-hello
    spec:
      containers:
        - name: flask-hello
          image: yahyasystementor/flask-eks-demo:1.0
          ports:
            - containerPort: 8080
