apiVersion: v1
kind: Service
metadata:
  name: flask-hello-lb
  annotations:
    server.beta.kubernetes.io/aws-load-balancer-schema: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: flask-hello
  ports:
    - port: 80
      targetPort: 8080
